#!/usr/bin/python

import argparse
import json
import sys

from dwhois.query import DWhois, QueryError
from dwhois.config import user,password,api_base_url

parser = argparse.ArgumentParser()
parser.add_argument('domains', help='list of domains', nargs='*')
parser.add_argument('--json','-j', help='json output', action='store_true')
parser.add_argument('--files','-f', help='file with domains', nargs='*')
parser.add_argument('--check','-c', help='check instead of get', action='store_true')
parser.add_argument('--submit','-s', help='submit domains', action='store_true')
args = parser.parse_args()

if not args.files and not args.domains:
    parser.error('Domains or files required')

def format(blob, out):
    print 'Domain: %s' % blob['domain_name']
    print 'Submitted: %d' % blob['submitted']
    print blob['whois']
    print '--EOF--'

dwhois = DWhois(api_base_url, user, password)

if args.files:
    for fn in args.files:
        if fn == '-':
            f = sys.stdin
        else:
            f = open(fn)

        for line in f:
            domain = line.strip()
            if not args.check and not args.submit:
                try:
                    if args.json:
                        print json.dumps(dwhois.get(domain))
                    else:
                        format(dwhois.get(domain), sys.stdout)
                except QueryError, e:
                    print 'Domain: %s' % domain
                    print 'ERROR: %s' % e.message
                    print '--EOF--'
            else:
                if args.check and args.submit:
                    if not dwhois.check(domain):
                        print 'Submitting: %s' % domain
                        dwhois.submit(domain)
                elif args.check:
                    print '%s: %s' % (domain, bool(dwhois.check(domain)))
                else:
                    dwhois.submit(domain)

        f.close()

for domain in args.domains:
    if not args.check and not args.submit:
        try:
            if args.json:
                print json.dumps(dwhois.get(domain))
            else:
                format(dwhois.get(domain), sys.stdout)
        except QueryError, e:
            print 'Domain: %s' % domain
            print 'ERROR: %s' % e.message
            print '--EOF--'
    else:
        if args.check and args.submit:
            if not dwhois.check(domain):
                print 'Submitting: %s' % domain
                dwhois.submit(domain)
        elif args.check:
            print '%s: %s' % (domain, bool(dwhois.check(domain)))
        else:
            dwhois.submit(domain)
