#!/usr/bin/python

import argparse
import sys

from dwhois.query import DWhois
from dwhois.config import user,password,api_base_url

parser = argparse.ArgumentParser()
parser.add_argument('domains', help='list of domains', nargs='*')
parser.add_argument('--files','-f', help='file with domains', nargs='*')
parser.add_argument('--check','-c', help='check instead of get', action='store_true')
parser.add_argument('--submit','-s', help='submit domains', action='store_true')
args = parser.parse_args()

if not args.files and not args.domains:
    parser.error('Domains or files required')

def format(blob, out):
    print 'Domain: %s' % blob['domain_name']
    print 'Submitted: %d' % blob['submitted']
    print blob['whois']
    print '--EOF--'

dwhois = DWhois(api_base_url, user, password)

if args.files:
    for fn in args.files:
        if fn == '-':
            f = sys.stdin
        else:
            f = open(fn)

        for line in f:
            domain = line.strip()
            if not args.check and not args.submit:
                format(dwhois.get(domain), sys.stdout)
            else:
                if args.check and args.submit:
                    if not dwhois.check(domain):
                        print 'Submitting: %s' % domain
                        dwhois.submit(domain)
                elif args.check:
                    print '%s: %s' % (domain, bool(dwhois.check(domain)))
                else:
                    dwhois.submit(domain)

        f.close()

for domain in args.domains:
    if not args.check and not args.submit:
        format(dwhois.get(domain), sys.stdout)
    else:
        if args.check and args.submit:
            if not dwhois.check(domain):
                print 'Submitting: %s' % domain
                dwhois.submit(domain)
        elif args.check:
            print '%s: %s' % (domain, bool(dwhois.check(domain)))
        else:
            dwhois.submit(domain)
